runtime: nodejs22
service: api

instance_class: F1

env_variables:
  NODE_ENV: 'production'
  DB_USER: 'your_db_user'
  DB_PASSWORD: 'your_db_password'
  DB_NAME: 'your_db_name'
  DB_HOST: '/cloudsql/your_cloud_sql_connection_name'
  GOOGLE_CLOUD_PROJECT: 'your_project_id'
  GOOGLE_APPLICATION_CREDENTIALS: 'path_to_your_service_account_key.json'
  GOOGLE_CLIENT_ID: 'your-google-client-id'
  GOOGLE_CLIENT_SECRET: 'your-google-client-secret'
  MODEL_BASE_URL: 'your-model-base-url'

automatic_scaling:
  target_cpu_utilization: 0.9
  min_instances: 0
  max_instances: 2
  idle_timeout: 10m

handlers:
  - url: /.*
    script: auto